# Copyright 2024 Canonical Limited
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = lint, unit

[vars]
application = data_platform_helpers
src_path = {tox_root}/data_platform_helpers
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
allowlist_externals =
    /bin/bash
    poetry

set_env =
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
    PYTHONBREAKPOINT=ipdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS
    LIBJUJU_VERSION_SPECIFIER

[testenv:format]
description = Apply coding style standards to code
commands =
    poetry install --only format
    poetry run ruff check --config pyproject.toml --fix {[vars]all_path}
    poetry run ruff format --config pyproject.toml {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
commands =
    poetry install -E all --with lint,format
    poetry run codespell {tox_root} \
        --skip {tox_root}/poetry.lock \
        --skip {tox_root}/.git \
        --skip {tox_root}/.tox \
        --skip {tox_root}/build \
        --skip {tox_root}/lib \
        --skip {tox_root}/venv \
        --skip {tox_root}/env \
        --skip {tox_root}/.mypy_cache \
        --skip {tox_root}/icon.svg 

    poetry run ruff check --config pyproject.toml {[vars]all_path}
    poetry run ruff format --config pyproject.toml --check --diff {[vars]all_path}
    poetry run pyright

[testenv:unit]
description = Run unit tests
set_env =
    {[testenv]set_env}
pass_env =
    {[testenv]pass_env}
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
commands_pre =
    poetry install --only main,unit
commands = poetry run coverage run --source={[vars]src_path} \
    -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit

[testenv:integration-db-v1]
description = Run database integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
    websockets{env:WEBSOCKETS_VERSION_SPECIFIER:}
commands_pre =
    poetry install --only main,integration
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_charm.py

[testenv:integration-kafka-v1]
description = Run Kafka integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
    websockets{env:WEBSOCKETS_VERSION_SPECIFIER:}
commands_pre =
    poetry install --only main,integration
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_kafka_charm.py

[testenv:integration-opensearch-v1]
description = Run opensearch integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
    websockets{env:WEBSOCKETS_VERSION_SPECIFIER:}
commands_pre =
    poetry install --only main,integration
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_opensearch_charm.py

[testenv:integration-etcd-v1]
description = Run charmed-etcd integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
    charmlibs-interfaces-tls-certificates>=1.1.0
allowlist_externals =
    {[testenv]allowlist_externals}
    # Set the testing host before starting the lxd cloud
    sudo
    apt-get
    tar
    mv
    wget
    etcdctl
    sh
commands_pre =
    sudo apt install wget -y
    sh -c "mkdir -p /tmp/etcd_install"
    sh -c 'if [ "$(uname -m)" = "aarch64" ]; then wget https://github.com/etcd-io/etcd/releases/download/v3.4.35/etcd-v3.4.35-linux-arm64.tar.gz -O /tmp/etcd_install/etcd.tar.gz; else wget https://github.com/etcd-io/etcd/releases/download/v3.4.35/etcd-v3.4.35-linux-amd64.tar.gz -O /tmp/etcd_install/etcd.tar.gz; fi'
    tar -xvf /tmp/etcd_install/etcd.tar.gz -C /tmp/etcd_install
    sh -c 'sudo mv /tmp/etcd_install/etcd-v3.4.35-linux-*/etcdctl /usr/local/bin'
    poetry install --only main,integration
commands =
    pytest -v --maxfail=1 --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_etcd_charm.py

[testenv:integration-kafka-connect-v1]
description = Run Kafka Connect integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
commands_pre =
    poetry install --only main,integration
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_kafka_connect_charm.py

[testenv:integration-backward-compatibility-v1]
description = Run backward compatibility integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
commands_pre =
    poetry install --only main,integration
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_backward_compatibility_charm.py

[testenv:integration-status-v1]
description = Run status/error propagation integration tests
deps =
    juju{env:LIBJUJU_VERSION_SPECIFIER:==3.6.1.3}
commands_pre =
    poetry install --only main,integration
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_status.py
